version: '3.8'

services:
  flask_app_v2:
    build: .  # Cambiar a la raíz del proyecto
    volumes:
      - ./srcs:/app  # Montar el código fuente desde srcs a /app dentro del contenedor
      - ./srcs/.env:/app/.env  # Montar el archivo .env dentro del contenedor
    ports:
      - "5000:5000"  # Puertos de la aplicación
    environment:
      - FLASK_ENV=development
    depends_on:
      - postgres_db
      - adminer

  postgres_db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    ports:
      - "8080:8080"

volumes:
  postgres_data:












