services:
  postgres:
    container_name: postgres_db
    image: postgres:alpine
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432/tcp"
    networks:
      - RedNet
    restart: always
    env_file:
      - .env

  flask:
    container_name: flask_app
    image: flask
    build: ./requirements/app
    volumes:
      - app:/app
    working_dir: /app
    ports:
      - "5000:5000"
      - "6969:5000"
    networks:
      - RedNet
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    networks:
      - RedNet
    ports:
      - "8080:8080"
      - "9876:8080"
    depends_on:
      - postgres

networks:
  RedNet:
    name: RedNet
    driver: bridge

volumes:
  database:
    name: ${POSTGRES_DB}
    driver: local
    driver_opts:
      type: volume
      device: ${PWD}/srcs/database
      o: bind
  app:
    name: BAXM_app
    driver: local
    driver_opts:
      type: volume
      device: ${PWD}/srcs/flask
      o: bind


