version: '3.8'

services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://Beaxabi:Beaxabi12345@db:5432/matcha_dev
    volumes:
      - .:/app
    depends_on:
      - db
    command: ["./wait-for-db.sh", "db", "flask", "run", "--host=0.0.0.0"]

  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: Beaxabi
      POSTGRES_PASSWORD: Beaxabi12345
      POSTGRES_DB: matcha_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "6969:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"  # O el puerto que elijas
    depends_on:
      - db

volumes:
  postgres_data:
