version: '3.8'

services:
  db:
    image: postgres:15
    container_name: matcha_db
    environment:
      POSTGRES_USER: Beaxabi
      POSTGRES_PASSWORD: Beaxabi12345
      POSTGRES_DB: matcha_dev
    ports:
      - "5433:5432"  # Mapear el puerto 5432 del contenedor al puerto 5433 de la máquina local
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  app:
    build: .
    container_name: matcha_app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - DATABASE_URL=${DATABASE_URL}  # Referencia a la variable en .env
      - SECRET_KEY=${SECRET_KEY}  # Referencia a la variable en .env
      - MAIL_USERNAME=${MAIL_USERNAME}  # Referencia a la variable en .env
      - MAIL_PASSWORD=${MAIL_PASSWORD}  # Referencia a la variable en .env
      - MAIL_DEFAULT_SENDER=${MAIL_DEFAULT_SENDER}  # Referencia a la variable en .env
      - SECURITY_PASSWORD_SALT=${SECURITY_PASSWORD_SALT}  # Referencia a la variable en .env
    volumes:
      - .:/app
    depends_on:
      - db
    command: bash -c "flask db upgrade && flask run --host=0.0.0.0"  # Ejecutar migraciones antes de iniciar la app

volumes:
  postgres_data:

