version: '3.8'  # Asegúrate de definir la versión de Docker Compose

services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://Beaxabi:Beaxabi12345@db:5432/matcha_dev
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: Beaxabi
      POSTGRES_PASSWORD: Beaxabi12345
      POSTGRES_DB: matcha_dev
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "6969:80"  # Escuchar en el puerto 80 del host
    volumes:
      - ./backend/nginx.conf:/etc/nginx/conf.d/default.conf  # Ajusta la ruta
    depends_on:
      - web

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com  # Cambia esto a tu email
      PGADMIN_DEFAULT_PASSWORD: admin  # Cambia esto a tu contraseña
    ports:
      - "8080:80"  # Acceso a pgAdmin en el puerto 8080
    depends_on:
      - db

volumes:
  postgres_data:






