services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://Beaxabi:Beaxabi12345@db:5432/matcha_dev
    volumes:
      - .:/app  # Montar el directorio actual en /app dentro del contenedor
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: Beaxabi
      POSTGRES_PASSWORD: Beaxabi12345
      POSTGRES_DB: matcha_dev
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistir datos

volumes:
  postgres_data:  # Volumen para almacenar datos de PostgreSQL

