services:
  postgres:
    container_name: BAXM_db
    image: postgres:alpine
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432/tcp"
    networks:
      - RedNet
    restart: always
    env_file:
      - .env

  nginx:
    container_name: BAXM_server
    image: nginx:alpine
    ports:
      - "6969:80/tcp"
    networks:
      - RedNet
    restart: always
    env_file:
      - .env
    volumes: # añadir root?
      - ./nginx.conf:/etc/nginx/nginx.conf
    # depends_on:
    #   - backend
    #   - frontend

  # backend:
  #   container_name: BAXM_backend
  #   image: python:3.10.12-alpine
  #   volumes:
  #     - ./backend:/app  # Aquí asumimos que el código Flask está en la carpeta backend
  #   working_dir: /app
  #   # command: flask run --host=0.0.0.0 --port=5000
  #   command: cat
    
  #   ports:
  #     - "5000:5000"
  #   networks:
  #     - RedNet
  #   depends_on:
  #     - postgres
  #   # restart: always
  #   env_file:
  #     - .env
  admined:
    container_name: adminer
    image: adminer
    restart: always
    networks:
      - RedNet
    ports:
      - "8080:8080"

networks:
  RedNet:
    name: RedNet
    driver: bridge


volumes:
  database:
    name: BAXM_db
    driver_opts:
      type: volume
      device: ${PWD}/srcs/database # tienen que existir
      o: bind


