version: '3.8'

services:
  backend:
    image: tiangolo/uwsgi-nginx-flask:python3.9
    volumes:
      - ./backend/app:/app
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://user:password@db:5432/tinder_db
    ports:
      - "5000:80"  # Exponemos el puerto 80 del contenedor al 5000

  frontend:
    image: node:14
    working_dir: /app
    volumes:
      - ./frontend/src:/app
    ports:
      - "8080:8080"  # El puerto por defecto para el servidor de desarrollo de Vue.js

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=tinder_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - db_data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

volumes:
  db_data:
